#!/bin/bash
# ============================================================
# InfraCommand — One-Time Server Setup Script
# 
# TWO ways to run this:
# 1. Manually (first time):  sudo bash setup.sh
# 2. Automatically via Jenkins pipeline (subsequent runs)
#
# This script is idempotent — safe to run multiple times
# ============================================================

set -e

NEXUS_REGISTRY="192.168.101.80:8082"
SUDOERS_FILE="/etc/sudoers.d/jenkins-infracommand"
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'

ok()   { echo -e "${GREEN}✔ $1${NC}"; }
warn() { echo -e "${YELLOW}⚠ $1${NC}"; }
err()  { echo -e "${RED}✘ $1${NC}"; }

echo ""
echo "============================================================"
echo "  InfraCommand Server Setup"
echo "  Nexus: ${NEXUS_REGISTRY}"
echo "============================================================"
echo ""

if [ "$EUID" -ne 0 ]; then
  err "Please run as root: sudo bash setup.sh"
  exit 1
fi
ok "Running as root"

# ── 1. Jenkins sudo rights (done FIRST so pipeline can use sudo) ──
echo ""
echo "[1/7] Configuring Jenkins sudo rights..."
mkdir -p /etc/sudoers.d
cat > ${SUDOERS_FILE} << SUDOEOF
# InfraCommand — Jenkins pipeline sudo permissions
# Auto-generated by setup.sh — do not edit manually
jenkins ALL=(ALL) NOPASSWD: /usr/bin/apt-get
jenkins ALL=(ALL) NOPASSWD: /usr/bin/crictl
jenkins ALL=(ALL) NOPASSWD: /usr/bin/ctr
jenkins ALL=(ALL) NOPASSWD: /usr/bin/docker
jenkins ALL=(ALL) NOPASSWD: /bin/bash
jenkins ALL=(ALL) NOPASSWD: /usr/bin/bash
jenkins ALL=(ALL) NOPASSWD: /usr/sbin/iptables
SUDOEOF
chmod 0440 ${SUDOERS_FILE}
ok "Jenkins sudo rights configured → ${SUDOERS_FILE}"

# ── 2. System packages ────────────────────────────────────────
echo ""
echo "[2/7] Installing required system packages..."
apt-get update -qq
apt-get install -y \
  python3-venv python3-pip python3-full python3-dev \
  build-essential curl wget git unzip \
  2>/dev/null || true
ok "System packages installed"

# ── 3. Verify python3-venv ────────────────────────────────────
echo ""
echo "[3/7] Verifying python3-venv..."
python3 -m venv /tmp/test-venv && rm -rf /tmp/test-venv
ok "python3-venv works"

# ── 4. Docker insecure registry ───────────────────────────────
echo ""
echo "[4/7] Configuring Docker insecure registry..."
mkdir -p /etc/docker
cat > /etc/docker/daemon.json << DOCKEREOF
{
  "insecure-registries": ["${NEXUS_REGISTRY}"]
}
DOCKEREOF
systemctl restart docker 2>/dev/null && ok "Docker restarted" || warn "Docker not running — skipping restart"
ok "Docker insecure registry → ${NEXUS_REGISTRY}"

# ── 5. CRI-O insecure registry ────────────────────────────────
echo ""
echo "[5/7] Configuring CRI-O insecure registry..."
if systemctl list-units --type=service 2>/dev/null | grep -q crio; then
  mkdir -p /etc/crio/crio.conf.d
  cat > /etc/crio/crio.conf.d/insecure-registry.conf << CRIOEOF
[crio.image]
insecure_registries = ["${NEXUS_REGISTRY}"]
CRIOEOF
  systemctl restart crio
  ok "CRI-O insecure registry → ${NEXUS_REGISTRY}"
else
  warn "CRI-O not running — skipping"
fi

# ── 6. containerd insecure registry ──────────────────────────
echo ""
echo "[6/7] Configuring containerd insecure registry..."
if command -v containerd &>/dev/null; then
  mkdir -p "/etc/containerd/certs.d/${NEXUS_REGISTRY}"
  cat > "/etc/containerd/certs.d/${NEXUS_REGISTRY}/hosts.toml" << CTDEOF
server = "http://${NEXUS_REGISTRY}"

[host."http://${NEXUS_REGISTRY}"]
  capabilities = ["pull", "resolve", "push"]
  skip_verify = true
CTDEOF
  # Ensure config_path is set under the correct CRI section
  if [ -f /etc/containerd/config.toml ]; then
    if grep -q "io.containerd.cri.v1.images" /etc/containerd/config.toml; then
      # containerd v2 style
      sed -i "/plugins.'io.containerd.cri.v1.images'.registry\]/,/config_path/{s|config_path = ''|config_path = '/etc/containerd/certs.d'|}" /etc/containerd/config.toml
    fi
  fi
  systemctl restart containerd 2>/dev/null && ok "containerd restarted" || warn "containerd not running"
  ok "containerd insecure registry → ${NEXUS_REGISTRY}"
else
  warn "containerd not found — skipping"
fi

# ── 7. Verify Jenkins sudo ─────────────────────────────────────
echo ""
echo "[7/7] Verifying Jenkins sudo rights..."
if id jenkins &>/dev/null; then
  sudo -u jenkins sudo -n crictl --version &>/dev/null \
    && ok "Jenkins → crictl sudo verified" \
    || warn "Jenkins crictl sudo test failed — check ${SUDOERS_FILE}"
  sudo -u jenkins sudo -n apt-get --version &>/dev/null \
    && ok "Jenkins → apt-get sudo verified" \
    || warn "Jenkins apt-get sudo test failed"
else
  warn "Jenkins user not found yet — sudo rights will apply once Jenkins is installed"
fi

# ── Summary ────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo -e "${GREEN}  Setup Complete!${NC}"
echo "============================================================"
echo ""
echo "  Nexus Docker Registry : http://${NEXUS_REGISTRY}"
echo "  Jenkins sudo rights   : ${SUDOERS_FILE} ✔"
echo "  Docker insecure reg   : configured ✔"
echo "  CRI-O insecure reg    : configured ✔"
echo "  containerd certs.d    : configured ✔"
echo ""
echo "  Next steps:"
echo "  1. Push infracommand/ to GitHub"
echo "  2. In Jenkins → New Item → Pipeline → point to your repo"
echo "  3. Add credentials (see README.md)"
echo "  4. Build Now"
echo ""
VM_IP=$(hostname -I | awk '{print $1}')
echo "  App URL: http://${VM_IP}:32302"
echo "============================================================"
echo ""
