sonar.projectKey=InfraCommand
sonar.projectName=InfraCommand
sonar.projectVersion=1.0
sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/build/**,**/venv/**,**/*.html,**/tests/**
sonar.python.version=3.11
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
