apiVersion: apps/v1
kind: Deployment
metadata:
  name: infracommand-backend
  namespace: infracommand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infracommand-backend
  template:
    metadata:
      labels:
        app: infracommand-backend
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: backend
          image: 192.168.101.80:8082/infracommand-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DB_PATH
              value: /data/infracommand.db
            - name: TRIVY_SERVER_URL
              value: "http://trivy-server.infracommand.svc.cluster.local:4954"
            - name: TRIVY_SERVER_EXTERNAL_URL
              value: "http://192.168.101.80:31954"
          volumeMounts:
            - name: db-storage
              mountPath: /data
      volumes:
        - name: db-storage
          hostPath:
            path: /opt/infracommand/db
            type: DirectoryOrCreate
      imagePullSecrets:
        - name: nexus-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: infracommand-backend
  namespace: infracommand
spec:
  selector:
    app: infracommand-backend
  ports:
    - port: 5000
      targetPort: 5000
