apiVersion: apps/v1
kind: Deployment
metadata:
  name: infracommand-backend
  namespace: infracommand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infracommand-backend
  template:
    metadata:
      labels:
        app: infracommand-backend
    spec:
      containers:
        - name: backend
          image: 192.168.101.80:8082/infracommand-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DB_PATH
              value: /data/infracommand.db
          volumeMounts:
            - name: db-storage
              mountPath: /data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: infracommand-db-pvc
      imagePullSecrets:
        - name: nexus-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: infracommand-backend
  namespace: infracommand
spec:
  selector:
    app: infracommand-backend
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infracommand-db-pvc
  namespace: infracommand
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
